# Generated by Django 4.2 on 2026-09-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'venues_venue',
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='venues.venue')),
            ],
            options={
                'verbose_name_plural': 'Seat Categories',
                'db_table': 'venues_seatcategory',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('seat_number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.seatcategory')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.venue')),
            ],
            options={
                'db_table': 'venues_seat',
                'unique_together': {('venue', 'row_number', 'seat_number')},
            },
        ),
    ]
