# Generated by Django 4.2 on 2026-10-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='hold_expires_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
    ]
