# Generated by Django 4.2 on 2026-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fan', 'Fan'), ('organizer', 'Event Organizer'), ('gate_staff', 'Gate Staff'), ('admin', 'Administrator')], default='fan', max_length=20),
        ),
    ]
