# Generated by Django 4.2 on 2026-10-05 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateentry',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gateentry',
            name='scanned_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gateentry',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_entries', to='tickets.ticket'),
        ),
    ]
